webtalk_init -webtalk_dir D:\\LINUX_TEST\\last_time\\last_time.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期一 三月 30 22:38:07 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cegf1lo1qncqm2krguhek87n02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1427725445387" -context "sdk\\\\hardware/1427725445387"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1427725445387"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1427725445387"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1427725445387"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1427725445387"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1427725445387"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1427725445387"
webtalk_add_data -client sdk -key uid -value "1427725481708" -context "sdk\\\\bsp/1427725481708"
webtalk_add_data -client sdk -key hwid -value "1427725445387" -context "sdk\\\\bsp/1427725481708"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1427725481708"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\bsp/1427725481708"
webtalk_add_data -client sdk -key uid -value "1427725483283" -context "sdk\\\\application/1427725483283"
webtalk_add_data -client sdk -key hwid -value "1427725445387" -context "sdk\\\\application/1427725483283"
webtalk_add_data -client sdk -key bspid -value "1427725481708" -context "sdk\\\\application/1427725483283"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1427725483283"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1427725483283"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\application/1427725483283"
webtalk_transmit -clientid 1985713496 -regid "" -xml D:\\LINUX_TEST\\last_time\\last_time.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\LINUX_TEST\\last_time\\last_time.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\LINUX_TEST\\last_time\\last_time.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
